# Generated by Django 4.2.7 on 2023-11-04 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(default=None, null=True)),
                ("steps", models.CharField(max_length=500)),
                (
                    "time_cook",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("author", models.CharField(max_length=70)),
                (
                    "photo",
                    models.ImageField(default=None, null=True, upload_to="media/"),
                ),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["title"], name="recipe_reci_title_4b9b8b_idx"),
                    models.Index(
                        fields=["author"], name="recipe_reci_author_4e0278_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("recipes", models.ManyToManyField(to="recipe.recipe")),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="recipe_cate_name_f59740_idx")
                ],
            },
        ),
    ]
